// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
// add css datepicker
import "react-datepicker/dist/react-datepicker.css";
// own css files here
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
//-------------------------------------------------------------------
import Mynavbar from '../component/menu/mynavbar'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header">
        <Mynavbar />
      </div>
      <div className='container'>
        <Component {...pageProps} />
      </div>
      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          CREDIT BY MIRACTECH
        </a>
      </footer>
    </div>
  )
}
export default MyApp
